// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzkezaykhjqthczdzrnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6a2V6YXlraGpxdGhjemR6cm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwODM0MDEsImV4cCI6MjA1NDY1OTQwMX0.KfeVpF0mIOIx1c9x8cjQPVzilRz7TT0ENH0_HoQmWs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);